modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/brdle/Delightful/issues"


[[mods]]
modId="delightful"
version="${file.jarVersion}"
displayName="Delightful"
displayURL="https://www.curseforge.com/minecraft/mc-mods/delightful"
updateJSONURL="https://brdle.net/delightful/update.json"
logoFile="delightful.png"
logoBlur=false
credits=""
authors="brdle"
description=""
itemIcon="minecraft:dirt"
configBackground="minecraft:textures/block/dirt.png"

[[dependencies.delightful]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.delightful]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.1,)"
    ordering="AFTER"
    side="BOTH"